remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

language: en
languages:
  - en
  - zh-CN


defaults:
  -
    scope:
      path: ""
      type: "README.md"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "README-cn.md"
    values:
      layout: "default"
  -
    scope:
      path: ""
    values:
      exclude: ["README.md", "README-cn.md"]

title: 
description: 